apiVersion: v1
kind: ServiceAccount
metadata:
  name: stillontime-sa
  namespace: stillontime
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: stillontime-sa
  namespace: stillontime-staging
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: stillontime
  name: stillontime-role
rules:
- apiGroups: [""]
  resources: ["pods", "services", "configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: stillontime-rolebinding
  namespace: stillontime
subjects:
- kind: ServiceAccount
  name: stillontime-sa
  namespace: stillontime
roleRef:
  kind: Role
  name: stillontime-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: stillontime-staging
  name: stillontime-role
rules:
- apiGroups: [""]
  resources: ["pods", "services", "configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: stillontime-rolebinding
  namespace: stillontime-staging
subjects:
- kind: ServiceAccount
  name: stillontime-sa
  namespace: stillontime-staging
roleRef:
  kind: Role
  name: stillontime-role
  apiGroup: rbac.authorization.k8s.io